Repository 21ow/codeit-FE10-3-Mogazoa, pull requests merged in 2024-12, with the labels that each got.

#3 feat: 아이콘 추가(로고x)
  public/images/icon/ic_add.svg
  public/images/icon/ic_bubble.svg
  public/images/icon/ic_category.svg
  public/images/icon/ic_close.svg
  public/images/icon/ic_dropdown.svg
  public/images/icon/ic_dropup.svg
  public/images/icon/ic_google.svg
  public/images/icon/ic_kakao.svg
  public/images/icon/ic_kakaotalk.svg
  public/images/icon/ic_menu.svg
  public/images/icon/ic_noheart.svg
  public/images/icon/ic_nothumb.svg
  public/images/icon/ic_novisibility.svg
  public/images/icon/ic_photo.svg
  public/images/icon/ic_profile.svg
  public/images/icon/ic_redheart.svg
  public/images/icon/ic_search.svg
  public/images/icon/ic_share.svg
  public/images/icon/ic_star.svg
  public/images/icon/ic_thumb.svg
  public/images/icon/ic_visibility.svg
Labels: ⚙ Setting

#7 fix: ESLint 설정 파일 수정
  .eslintrc.json
  eslint.config.mjs
  package-lock.json
  package.json
  src/app/layout.tsx
Labels: ⚙ Setting

#8 chore: 이슈 템플릿 타이틀 형식 수정
  .github/ISSUE_TEMPLATE/tesk.md
Labels: ⚙ Setting

#10 chore: API 함수 추가
  .gitignore
  src/_api/ImageApi.ts
  src/_api/authApi.ts
  src/_api/axiosInstance.ts
  src/_api/categoryApi.ts
  src/_api/constant/noTokenEndPoints.ts
  src/_api/followApi.ts
  src/_api/oauthApi.ts
  src/_api/productApi.ts
  src/_api/reviewApi.ts
  src/_api/storage/authStorage.ts
  src/_api/storage/localStorage.ts
  src/_api/storage/sessionStorage.ts
  src/_api/type/Auth.ts
  src/_api/type/Category.ts
  src/_api/type/Follow.ts
  src/_api/type/Image.ts
  src/_api/type/Oauth.ts
  src/_api/type/Product.ts
  src/_api/type/Review.ts
  src/_api/type/User.ts
  src/_api/userApi.ts
  src/_api/util/isAuthRequired.ts
Labels: 📬 API

#9 style:공용 스타일 css 추가
  next.config.ts
  src/app/globals.css
  src/app/globals.scss
  src/app/layout.tsx
  src/assets/reset.scss
  src/assets/variables.scss
Labels: ⚙ Setting

#14 setting: 모가조아 로고 추가
  public/images/img/img_catbody.svg
  public/images/img/img_cateyes.svg
  public/images/img/img_logo.svg
Labels: ⚙ Setting

#15 chore: 이미지 파일 이름 변경
  public/icon/ic-add.svg
  public/icon/ic-bubble.svg
  public/icon/ic-category.svg
  public/icon/ic-close.svg
  public/icon/ic-dropdown.svg
  public/icon/ic-dropup.svg
  public/icon/ic-google.svg
  public/icon/ic-heart-select.svg
  public/icon/ic-heart.svg
  public/icon/ic-invisibility.svg
  public/icon/ic-kakaotalk.svg
  public/icon/ic-menu.svg
  public/icon/ic-photo.svg
  public/icon/ic-profile.svg
  public/icon/ic-search.svg
  public/icon/ic-share.svg
  public/icon/ic-star.svg
  public/icon/ic-thumb-select.svg
  public/icon/ic-thumb.svg
  public/icon/ic-visibility.svg
  public/images/icon/ic_kakao.svg
  public/img/img-catbody.svg
  public/img/img-cateyes.svg
  public/img/img-logo.svg
Labels: 🧹 chore

#17 chore: 디테일 수정
  package.json
  src/_asset/reset.scss
  src/_asset/variables.scss
  src/app/globals.scss
Labels: 🧹 Chore

#19 chore: 공용 스타일 파일 디테일 수정
  next.config.ts
  src/app/globals.scss
  src/asset/reset.scss
  src/asset/variables.scss
Labels: ⚙ Setting

#21 chore: 폴더명 수정
  public/image/img-catbody.svg
  public/image/img-cateyes.svg
  public/image/img-logo.svg
  src/api/ImageApi.ts
  src/api/authApi.ts
  src/api/axiosInstance.ts
  src/api/categoryApi.ts
  src/api/constant/noTokenEndPoints.ts
  src/api/followApi.ts
  src/api/oauthApi.ts
  src/api/productApi.ts
  src/api/reviewApi.ts
  src/api/storage/authStorage.ts
  src/api/storage/localStorage.ts
  src/api/storage/sessionStorage.ts
  src/api/type/Auth.ts
  src/api/type/Category.ts
  src/api/type/Follow.ts
  src/api/type/Image.ts
  src/api/type/Oauth.ts
  src/api/type/Product.ts
  src/api/type/Review.ts
  src/api/type/User.ts
  src/api/userApi.ts
  src/api/util/isAuthRequired.ts
  src/shared/Input.tsx
Labels: 🧹 Chore

#25 feat: 공용 버튼 UI 구현 #11
  src/app/page.module.scss
  src/app/page.tsx
  src/shared/button/Button.module.scss
  src/shared/button/Button.tsx
Labels: ✨ Feature

#27 chore: svgr 기능 추가 및 svg 자체 색상 삭제
  next.config.ts
  package-lock.json
  package.json
  public/image/img-catbody.svg
  public/image/img-cateyes.svg
  public/image/img-logo.svg
Labels: ⚙ Setting

#29 feat: 공통 쿼리 훅 구현
  src/api/ImageApi.ts
  src/api/apiEndpoints.ts
  src/api/authApi.ts
  src/api/authStorage.ts
  src/api/categoryApi.ts
  src/api/constant/noTokenEndPoints.ts
  src/api/followApi.ts
  src/api/oauthApi.ts
  src/api/productApi.ts
  src/api/reviewApi.ts
  src/api/storage/authStorage.ts
  src/api/storage/localStorage.ts
  src/api/storage/sessionStorage.ts
  src/api/useCustomMutation.ts
  src/api/useCustomQuery.ts
  src/api/userApi.ts
  src/api/util/httpUtils.ts
  src/api/util/isAuthRequired.ts
  src/lib/axiosInstance.ts
  src/util/webStorage.ts
Labels: ✨ Feature, 🔨 Refactor

#28 feat: 공용 인풋 컴포넌트 구현
  public/icon/ic-img-upload.svg
  src/asset/reset.scss
  src/asset/variables.scss
  src/hook/useTextCounter.ts
  src/shared/Input.tsx
  src/shared/Input/Input.module.scss
  src/shared/Input/Input.tsx
  src/shared/Input/component/ErrorMessage.module.scss
  src/shared/Input/component/ErrorMessage.tsx
  src/shared/Input/component/FileLabel.tsx
  src/shared/Input/component/FilePreview.module.scss
  src/shared/Input/component/FilePreview.tsx
  src/shared/Input/component/InfoMessage.module.scss
  src/shared/Input/component/InfoMessage.tsx
  src/shared/Input/component/Label.module.scss
  src/shared/Input/component/Label.tsx
  src/shared/Input/component/PwToggleBtn.module.scss
  src/shared/Input/component/PwToggleBtn.tsx
  src/shared/Input/hook/useInput.ts
  src/shared/TextArea/TextArea.module.scss
  src/shared/TextArea/TextArea.tsx
  src/shared/TextCount.tsx
Labels: ✨ Feature

#30 chore: 디테일 수정
  public/image/img-logo.svg
  src/app/globals.scss
  src/app/page.module.scss
  src/app/page.tsx
  src/asset/reset.scss
  src/asset/variables.scss
  src/shared/Input/Input.module.scss
Labels: 🧹 Chore

#34 refactor: 공용 인풋 피드백 반영
  package-lock.json
  package.json
  src/hook/useTextCounter.ts
  src/shared/Input/Input.module.scss
  src/shared/Input/Input.tsx
  src/shared/Input/component/PwToggleBtn.tsx
  src/shared/Input/hook/useImageUpload.ts
  src/shared/Input/hook/usePasswordToggle.ts
  src/shared/TextArea/TextArea.tsx
  src/shared/TextCount.tsx
Labels: 🔨 Refactor

#31 feat: 공용 모달 임시 작업
  src/shared/modal/Modal.module.scss
  src/shared/modal/Modal.tsx
  src/shared/modal/ModalHeader.module.scss
  src/shared/modal/ModalHeader.tsx
  src/shared/modal/useModalStore.ts
Labels: ✨ Feature

#35 fix: 공용 쿼리 훅 수정
  next.config.ts
  src/api/ImageApi.ts
  src/api/apiEndpoints.ts
  src/api/authApi.ts
  src/api/authStorage.ts
  src/api/categoryApi.ts
  src/api/followApi.ts
  src/api/oauthApi.ts
  src/api/productApi.ts
  src/api/reviewApi.ts
  src/api/storage/authStorage.ts
  src/api/storage/localStorage.ts
  src/api/storage/sessionStorage.ts
  src/api/useCustomMutation.ts
  src/api/useCustomQuery.ts
  src/api/userApi.ts
  src/api/util/httpUtils.ts
  src/lib/axiosInstance.ts
  src/util/webStorage.ts
Labels: 🐞 BugFix

#39 feat: 공용 헤더 컴포넌트 구현
  src/asset/variables.scss
  src/shared/navigation/Navigation.module.scss
  src/shared/navigation/Navigation.tsx
Labels: ✨ Feature

#38 chore: 허스키 파일 및 훅 추가
  .husky/pre-commit
  package-lock.json
  package.json
Labels: ⚙ Setting

#45 feat: 공용 헤더 컴포넌트 수정
  src/shared/navigation/Navigation.module.scss
  src/shared/navigation/Navigation.tsx
Labels: ✨ Feature

#47 chore: button 구조 수정
  src/shared/button/Button.tsx
Labels: 🧹 Chore
