Repository 21ow/codeit-FE10-3-Mogazoa, pull requests merged in 2025-01, with the labels that each got.

#57 fix: github desktop에서 커밋안되던 오류 수정
  .husky/pre-commit
Labels: 🐞 BugFix

#59 fix: 모달 에러 수정
  src/shared/modal/Modal.module.scss
  src/shared/modal/Modal.tsx
  src/shared/modal/ModalHeader.module.scss
  src/shared/modal/ModalHeader.tsx
  src/shared/modal/useModalStore.ts
Labels: 🐞 BugFix, 🎨 HTML&CSS

#58 feat: 이미지 컴포넌트, 상품카드 컴포넌트 제작
  next.config.ts
  src/api/productApi.ts
  src/api/type/Category.ts
  src/api/type/Product.ts
  src/app/page.tsx
  src/feature/landingpage/ProductCard/ProductCard.module.scss
  src/feature/landingpage/ProductCard/ProductCard.tsx
  src/feature/landingpage/ProductImage/ProductImage.module.scss
  src/feature/landingpage/ProductImage/ProductImage.tsx
  src/feature/landingpage/Products.module.scss
  src/feature/landingpage/Products.tsx
  src/feature/landingpage/ProductsPage/BestProducts.module.scss
  src/feature/landingpage/ProductsPage/BestProducts.tsx
  src/feature/landingpage/ProductsPage/RatingProducts.module.scss
  src/feature/landingpage/ProductsPage/RatingProducts.tsx
  src/lib/axiosInstance.ts
  tsconfig.json
Labels: ✨ Feature

#60 feat: 리뷰어 리스트 추가
  src/feature/landingpage/ProductCard/ProductCard.module.scss
  src/feature/landingpage/ProductImage/ProductImage.tsx
  src/feature/landingpage/Products.module.scss
  src/feature/landingpage/Products.tsx
  src/feature/landingpage/ProductsPage/BestProducts.module.scss
  src/feature/landingpage/ProductsPage/BestProducts.tsx
  src/feature/landingpage/ProductsPage/RatingProducts.module.scss
  src/feature/landingpage/RankingList/RankingList.module.scss
  src/feature/landingpage/RankingList/RankingList.tsx
Labels: ✨ Feature

#70 feat: 공통 api 함수 구현
  package-lock.json
  package.json
  src/api/createQueries.ts
  src/api/storage/authStorage.ts
  src/lib/axiosInstance.ts
Labels: 📬 API

#67 feat: 커스텀 모달 스타일 props 추가
  src/shared/modal/Modal.module.scss
  src/shared/modal/Modal.tsx
Labels: ✨ Feature

#69 chore: api 에러 처리 관심사 분리
  src/api/ImageApi.ts
  src/api/authApi.ts
  src/api/categoryApi.ts
  src/api/followApi.ts
  src/api/oauthApi.ts
  src/api/productApi.ts
  src/api/type/Product.ts
  src/api/type/User.ts
  src/api/userApi.ts
  src/feature/landingpage/ProductsPage/BestProducts.tsx
  src/feature/landingpage/ProductsPage/RatingProducts.tsx
Labels: 📬 API

#78 feat: 로그인/회원가입 구현
  package-lock.json
  package.json
  public/icon/ic-add-item.svg
  public/icon/ic-compare.svg
  public/icon/ic-search.svg
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/app/globals.scss
  src/app/layout.tsx
  src/asset/variables.scss
  src/feature/auth/component/SocialSiginin.module.scss
  src/feature/auth/component/SocialSignin.tsx
  src/feature/auth/signin/Signin.module.scss
  src/feature/auth/signin/Signin.tsx
  src/feature/auth/signup/Signup.module.scss
  src/feature/auth/signup/Signup.tsx
  src/shared/navigation/Navigation.module.scss
  src/shared/navigation/Navigation.tsx
Labels: ✨ Feature

#73 feat: 공용 드롭다운 1차 개발
  src/shared/dropdown/Dropdown.module.scss
  src/shared/dropdown/Dropdown.tsx
  src/shared/dropdown/useDropdown.ts
Labels: ✨ Feature

#81 feat: 유저 프로필 페이지 1차 개발
  src/feature/profile/UserProfile.module.scss
  src/feature/profile/UserProfile.tsx
  src/feature/profile/details/UserDetails.module.scss
  src/feature/profile/details/UserDetails.tsx
  src/feature/profile/history/UserHistory.module.scss
  src/feature/profile/history/UserHistory.tsx
  src/feature/profile/reviewed/UserReviewedProduct.module.scss
  src/feature/profile/reviewed/UserReviewedProduct.tsx
Labels: ✨ Feature

#79 feat: 댓글 페이지 코드 제작
  public/icon/ic-bubble.svg
  public/icon/ic-heart-select.svg
  public/icon/ic-heart.svg
  public/icon/ic-star.svg
  src/api/productApi.ts
  src/app/globals.scss
  src/app/page.tsx
  src/app/product/[id]/page.tsx
  src/app/product/[id]/styles.module.scss
  src/app/product/page.tsx
  src/feature/landingpage/Comment/Comment.tsx
  src/feature/landingpage/Comment/styles.module.scss
  src/feature/landingpage/DataForm/DataForm.tsx
  src/feature/landingpage/DataForm/LikeForm/LikeForm.tsx
  src/feature/landingpage/DataForm/styles.module.scss
  src/feature/landingpage/DataForm/useFavoriteStore.ts
  src/feature/landingpage/HeartCheck/HeartCheck.tsx
  src/feature/landingpage/HeartCheck/styles.module.scss
  src/feature/landingpage/PagiNation/PagiNation.module.scss
  src/feature/landingpage/PagiNation/PagiNation.tsx
  src/feature/landingpage/ProductCard/ProductCard.tsx
  src/feature/landingpage/ProductsPage/BestProducts.module.scss
  src/feature/landingpage/RankingList/RankingList.module.scss
  src/feature/landingpage/RankingList/RankingList.tsx
  src/feature/landingpage/RatingStar/RatingStar.tsx
  src/feature/landingpage/RatingStar/styles.module.scss
  src/shared/Image/Images.tsx
Labels: ✨ Feature

#82 feat: 드롭다운 2차 개발
  src/shared/dropdown/Dropdown.module.scss
  src/shared/dropdown/Dropdown.tsx
  src/shared/dropdown/useDropdownStore.ts
Labels: 🐞 BugFix, ✨ Feature

#84 chore: 공용 드롭다운 3차 개발
  src/shared/dropdown/Dropdown.module.scss
  src/shared/dropdown/Dropdown.tsx
Labels: 🧹 Chore

#90 feat: 토큰 전역 상태관리 로직 추가
  src/api/reviewApi.ts
  src/api/storage/localStorage.ts
  src/api/storage/sessionStorage.ts
  src/api/userApi.ts
  src/api/util/isAuthRequired.ts
  src/constant/message.ts
  src/feature/auth/signin/Signin.tsx
  src/feature/auth/signup/Signup.tsx
  src/lib/axiosInstance.ts
  src/shared/input/Input.module.scss
  src/shared/input/Input.tsx
  src/shared/input/component/ErrorMessage.module.scss
  src/shared/input/component/ErrorMessage.tsx
  src/shared/input/component/FileLabel.tsx
  src/shared/input/component/FilePreview.module.scss
  src/shared/input/component/FilePreview.tsx
  src/shared/input/component/InfoMessage.module.scss
  src/shared/input/component/InfoMessage.tsx
  src/shared/input/component/Label.module.scss
  src/shared/input/component/Label.tsx
  src/shared/input/component/PwToggleBtn.module.scss
  src/shared/input/component/PwToggleBtn.tsx
  src/shared/input/hook/useImageUpload.ts
  src/shared/input/hook/usePasswordToggle.ts
  src/shared/navigation/Navigation.module.scss
  src/shared/navigation/Navigation.tsx
  src/store/useAuthStore.ts
Labels: 📬 API

#92 chore: 데이터 패칭 및 토큰 설정 추출 로직 수정
  src/feature/auth/signin/Signin.tsx
  src/feature/auth/signup/Signup.tsx
Labels: 🐞 BugFix

#95 feat: 레이아웃 추가
  package-lock.json
  package.json
  src/app/layout.module.scss
  src/app/layout.tsx
  src/app/page.tsx
  src/asset/globals.scss
  src/asset/reset.scss
  src/asset/variables.scss
  src/feature/landingpage/Products.tsx
  src/feature/landingpage/ProductsPage/BestProducts.module.scss
  src/feature/landingpage/ProductsPage/RatingProducts.module.scss
  src/feature/landingpage/RankingList/RankingList.module.scss
  src/shared/category/Category.module.scss
  src/shared/category/Category.tsx
  src/shared/navigation/Navigation.module.scss
  src/shared/navigation/Navigation.tsx
  src/shared/navigation/component/MobileMenu.module.scss
  src/shared/navigation/component/MobileMenu.tsx
  src/shared/navigation/component/NavMenu.module.scss
  src/shared/navigation/component/NavMenu.tsx
  src/shared/navigation/component/UserActions.module.scss
  src/shared/navigation/component/UserActions.tsx
  src/shared/navigation/component/UserProfile.module.scss
  src/shared/navigation/component/UserProfile.tsx
Labels: ✨ Feature

#98 feat: 풀 페이지 레이아웃 구현
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/app/layout.module.scss
  src/app/layout.tsx
  src/feature/auth/component/SocialSiginIn.module.scss
  src/feature/auth/component/SocialSignIn.tsx
  src/feature/auth/signin/SignIn.module.scss
  src/feature/auth/signin/SignIn.tsx
  src/feature/auth/signup/SignUp.module.scss
  src/feature/auth/signup/SignUp.tsx
Labels: ✨ Feature

#100 feat: review 모달 개발 및 기존 모달 창 수정& axiosInstance 수정
  src/app/product/[id]/page.tsx
  src/feature/landingpage/Button/ReviewButton.tsx
  src/feature/landingpage/DataForm/DataForm.tsx
  src/feature/landingpage/HeartCheck/HeartCheck.tsx
  src/feature/landingpage/ProductCard/ProductCard.tsx
  src/feature/landingpage/ReviewModal/ImageContain.module.scss
  src/feature/landingpage/ReviewModal/ImageContain.tsx
  src/feature/landingpage/ReviewModal/ReviewModal.tsx
  src/feature/landingpage/ReviewModal/StarRating.tsx
  src/feature/landingpage/ReviewModal/styles.module.scss
  src/lib/axiosInstance.ts
  src/shared/modal/Modal.module.scss
  src/shared/modal/ModalHeader.module.scss
  src/shared/modal/ModalHeader.tsx
Labels: ✨ Feature

#101 feat: 경로 수정 및 쿼리 옵션 추가
  src/api/createQueries.ts
  src/api/util/isAuthRequired.ts
Labels: ✨ Feature

#105 feat: 상품 등록 페이지 구현
  src/app/add-product/page.tsx
  src/feature/add-product/addProduct.module.scss
  src/feature/add-product/addProduct.tsx
  src/shared/TextArea/TextArea.module.scss
  src/shared/navigation/Navigation.tsx
  src/shared/navigation/component/NavMenu.tsx
Labels: ✨ Feature

#106 feat: onChange 결합
  src/shared/TextArea/TextArea.tsx
  src/shared/input/Input.tsx
Labels: ✨ Feature

#107 chore: 누락 코드 추가
  src/api/util/isAuthRequired.ts
  src/app/page.tsx
  src/store/useAuthStore.ts
Labels: 🧹 Chore

#110 feat: 실시간 필터링 기능 1차 개발
  src/shared/filtering/Filtering.tsx
  src/shared/filtering/useFilteringStore.ts
Labels: ✨ Feature

#111 fix: 드롭다운 선택값 고정 이슈 해결
  src/shared/dropdown/Dropdown.module.scss
  src/shared/dropdown/Dropdown.tsx
  src/shared/dropdown/useDropdownStore.ts
Labels: 🐞 BugFix, ✨ Feature, 🧹 Chore

#113 chore: 로직 개선 및 예외처리
  src/api/util/isAuthRequired.ts
  src/app/page.tsx
  src/constant/message.ts
  src/feature/auth/signin/SignIn.tsx
  src/feature/auth/signup/SignUp.tsx
  src/lib/axiosInstance.ts
  src/lib/localStorage.ts
  src/shared/navigation/component/MobileMenu.tsx
  src/shared/navigation/component/UserActions.tsx
  src/store/useAuthStore.ts
Labels: 🐞 BugFix, 🔨 Refactor

#114 feat: 디테일 추가
  next.config.ts
  public/icon/ic-menu.svg
  src/api/util/isAuthRequired.ts
  src/app/layout.tsx
  src/asset/mixins.scss
  src/asset/variables.scss
  src/feature/add-product/addProduct.module.scss
  src/feature/add-product/addProduct.tsx
  src/feature/auth/signin/SignIn.module.scss
  src/feature/auth/signin/SignIn.tsx
  src/feature/auth/signup/SignUp.module.scss
  src/feature/auth/signup/SignUp.tsx
  src/hook/useAuthGuard.ts
  src/shared/category/Category.module.scss
  src/shared/input/Input.module.scss
  src/shared/input/Input.tsx
  src/shared/input/component/FilePreview.module.scss
  src/shared/input/component/FilePreview.tsx
  src/shared/input/component/Label.module.scss
  src/shared/input/component/Label.tsx
  src/shared/logo/logo.tsx
  src/shared/navigation/Navigation.tsx
  src/shared/navigation/component/MobileMenu.module.scss
  src/shared/navigation/component/MobileMenu.tsx
Labels: ✨ Feature

#115 feat:댓글 수정 및 삭제 컴포넌트 추가(globals layout 수정)
  src/api/type/Review.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/product/[id]/page.tsx
  src/app/product/[id]/styles.module.scss
  src/app/product/page.tsx
  src/feature/landingpage/Button/ReviewButton.tsx
  src/feature/landingpage/CategoryChip/CategoryChip.tsx
  src/feature/landingpage/CategoryChip/styles.module.scss
  src/feature/landingpage/Comment/Comment.tsx
  src/feature/landingpage/Comment/Delete/ReviewDelete.module.scss
  src/feature/landingpage/Comment/Delete/ReviewDelete.tsx
  src/feature/landingpage/Comment/Edit/ReviewEdit.module.scss
  src/feature/landingpage/Comment/Edit/ReviewEdit.tsx
  src/feature/landingpage/Comment/styles.module.scss
  src/feature/landingpage/DataForm/DataForm.tsx
  src/feature/landingpage/DataForm/LikeForm/LikeForm.tsx
  src/feature/landingpage/DataForm/styles.module.scss
  src/feature/landingpage/IdProducts.module.scss
  src/feature/landingpage/IdProducts.tsx
  src/feature/landingpage/ReviewModal/ImageContain.module.scss
  src/feature/landingpage/ReviewModal/ImageContain.tsx
  src/feature/landingpage/ReviewModal/ReviewModal.tsx
  src/feature/landingpage/ReviewModal/StarRating.tsx
Labels: ✨ Feature

#116 feat: 상품 등록 페이지 로직, 스타일링 추가
  src/api/query.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/feature/add-product/addProduct.module.scss
  src/feature/add-product/addProduct.tsx
  src/feature/auth/signin/SignIn.tsx
  src/feature/auth/signup/SignUp.tsx
  src/hook/useAuthGuard.ts
  src/lib/axiosInstance.ts
  src/lib/createQueries.ts
  src/lib/localStorage.ts
  src/shared/TextArea/TextArea.module.scss
  src/shared/category/Category.tsx
  src/shared/input/Input.module.scss
  src/shared/input/Input.tsx
  src/shared/input/component/FilePreview.tsx
  src/shared/input/component/Label.module.scss
  src/shared/input/component/Label.tsx
  src/shared/modal/Modal.tsx
  src/shared/navigation/component/MobileMenu.module.scss
  src/shared/navigation/component/MobileMenu.tsx
  src/shared/navigation/component/UserActions.tsx
  src/shared/navigation/component/UserProfile.tsx
  src/store/useAuthStore.ts
Labels: ✨ Feature

#118 feat: 디테일 기능 추가
  public/image/img-catbody.svg
  src/api/query.ts
  src/app/layout.module.scss
  src/feature/landingpage/Products.module.scss
  src/feature/landingpage/ProductsPage/BestProducts.module.scss
  src/feature/landingpage/ProductsPage/BestProducts.tsx
  src/feature/landingpage/ProductsPage/RatingProducts.module.scss
  src/feature/landingpage/ProductsPage/RatingProducts.tsx
  src/feature/landingpage/RankingList/RankingList.module.scss
  src/feature/landingpage/RankingList/RankingList.tsx
  src/lib/createQueries.ts
  src/shared/category/Category.tsx
  src/shared/empty/Empty.module.scss
  src/shared/empty/Empty.tsx
  src/shared/navigation/component/MobileMenu.tsx
  src/shared/navigation/component/NavMenu.tsx
  src/store/useCategoryStore.ts
Labels: ✨ Feature

#119 feat: comment DropDown 추가(styles 제외)
  src/app/product/[id]/styles.module.scss
  src/feature/landingpage/Comment/Comment.tsx
  src/feature/landingpage/Comment/styles.module.scss
  src/feature/landingpage/IdProducts.module.scss
  src/feature/landingpage/IdProducts.tsx
  src/feature/landingpage/ProductCard/ProductCard.module.scss
  src/feature/landingpage/ProductCard/ProductCard.tsx
  src/feature/landingpage/ProductsPage/BestProducts.module.scss
Labels: ✨ Feature

#121 feat: 본인 리뷰일 때만 수정 삭제 버튼 보일 수 있도록 기능 추가
  src/feature/landingpage/Comment/Comment.tsx
Labels: ✨ Feature

#120 feat: 편집 버튼 추가
  src/feature/landingpage/Button/CompareButton.tsx
  src/feature/landingpage/Button/EditButton.tsx
  src/feature/landingpage/Button/styles.module.scss
  src/feature/landingpage/Comment/styles.module.scss
  src/feature/landingpage/DataForm/styles.module.scss
  src/feature/landingpage/IdProducts.module.scss
  src/feature/landingpage/IdProducts.tsx
Labels: ✨ Feature

#124 feat: 디테일 기능 추가
  package-lock.json
  package.json
  src/api/query.ts
  src/app/layout.module.scss
  src/feature/add-product/addProduct.tsx
  src/feature/landingpage/ProductsPage/BestProducts.tsx
  src/feature/landingpage/ProductsPage/RatingProducts.tsx
  src/lib/createQueries.ts
  src/shared/category/Category.module.scss
  src/shared/dropdown/Dropdown.tsx
  src/shared/dropdown/useDropdownStore.ts
  src/shared/navigation/component/MobileMenu.module.scss
  src/shared/navigation/component/MobileMenu.tsx
  src/shared/navigation/component/UserDashboard.module.scss
  src/shared/navigation/component/UserDashboard.tsx
  src/shared/navigation/component/UserProfile.module.scss
  src/shared/navigation/component/UserProfile.tsx
  src/shared/navigation/hook/useUserActions.ts
Labels: ✨ Feature

#123 feat: 프로필 편집 모달 구현
  src/feature/profile/modal/EditButton.tsx
  src/feature/profile/modal/ProfileEdit.tsx
  src/feature/profile/modal/styles.module.scss
Labels: ✨ Feature

#127 feat: 구현
  package-lock.json
  package.json
  public/icon/ic-star2.svg
  src/api/query.ts
  src/app/compare/page.tsx
  src/app/mypage/page.tsx
  src/feature/compare/Compare.module.scss
  src/feature/compare/Compare.tsx
  src/feature/compare/inputs/Inputs.module.scss
  src/feature/compare/inputs/Inputs.tsx
  src/feature/compare/result/Result.module.scss
  src/feature/compare/result/Result.tsx
  src/feature/compare/useCompareStore.ts
  src/feature/profile/UserProfile.module.scss
  src/feature/profile/UserProfile.tsx
  src/feature/profile/details/UserDetails.tsx
  src/feature/profile/history/UserHistory.module.scss
  src/feature/profile/history/UserHistory.tsx
  src/feature/profile/reviewed/UserReviewedProduct.tsx
  src/shared/dropdown/Dropdown.tsx
  src/shared/filtering/Filtering.tsx
Labels: 🐞 BugFix, ✨ Feature, 📬 API, 🧹 Chore
